### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by yurakuzh** [dark-side/language-school#44]
<img width="1035" alt="screen shot 2015-08-15 at 2 59 53 pm" src="https://cloud.githubusercontent.com/assets/3832666/9288715/5c49752a-435e-11e5-85aa-859cc14ade61.png">
 Does it work as expected?

**Comment by yurko** [comment]
please specify the steps that lead to errors. Just checked, it works as expected

![image](https://cloud.githubusercontent.com/assets/639535/9289287/8e2b9356-4373-11e5-9b0e-d4d7e7163d86.png)

**Comment by yurakuzh** [comment]
click "comment" button when input is empty

**Comment by yurko** [comment]
got it) because of the lack of the time it was agreed to implement validation only at the server side. The same issue is with Menu. Will add a fix.

**Comment by yurakuzh** [comment]
try to use flash messages when add something and confirmation + fash messages when remove
